title: Your awesome title
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
    "Asdasdasdasdasdasdasdasd\-''"

baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://cyobb.com/testingg" # the base hostname & protocol for your site
twitter_username: jekyllrb

markdown: kramdown

name: Your awesome title

date: 2017-05-09 17:23:11 +0000
permalink: /:year/:month/:day/:title

logo: false
paginate: 10
domain_name: http://cyobb.com/testingg/
google_analytics: UA-31XXXXXX-X
gems: [jekyll-paginate]
cover: 
author_image: 
# Details for the RSS feed generator
author:        testingg
